### PR TITLE
Added About

### PR DESCRIPTION
**Pull request by velascoDev**
-Added About Page 
-Added About and Home links
-Separated CSS from index.html into index.css
-Created about.css
-Added About route

### CODE REVIEW

**Comment by velascoDev** [comment]
-Added About Page 
-Added About and Home links
-Separated CSS from index.html into index.css
-Created about.css
-Added About route

**Comment by joshghent** [comment]
@velascoDev Brilliant, that's great. Thank you very much! Look forward to your next PR! 🎉

**Comment by velascoDev** [comment]
No problem. Obviously, it's really simple but let me know if you would like me to spice it up. Next, I'd like to work on the loading external library feature.

**Comment by joshghent** [comment]
@velascoDev No it looks great, thanks a lot.

Make a comment on [that issue](https://github.com/esfiddle/esfiddle/issues/46) and we will discuss it there 👍

**Pull request merged**
