### PR TITLE
Fix: #113 - inline critical css, optimize css delivery, and remove render blocking js

### LINKED ISSUE #113: Avoid render blocking JS and CSS requests
With the new redesign of the site we introduced a couple of dependancies on fontawesome and ballon.css. We need to make sure these assets are accessed async with the rest of the page and that they do not block the rendering of the page. We want to minimize network requests where available. 

Along with fixing the render blocking requests, bonus points on this PR for having fallbacks for the icons on the page in case the network request to fontawesome times out.

A screenshot can be found below that was taken from Google PSI. The full results for the site can be found [here](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fesfiddle.net&tab=mobile).
image

If you need any help with this issue then please let us know. We'd be happy to help. You can also check out our [contributing](https://github.com/esfiddle/esfiddle/blob/develop/docs/CONTRIBUTE.md) guide 👍

### PR DESCRIPTION
**Pull request by collinmesser**
#### Pre-Submission Checklist
- [x] Your pull request targets the `develop` branch.
- [x] Branch starts with either `fix/` or `feature/`
- [x] All new and existing tests pass the command `npm test`.
- [ ] Any new files are included in the grunt tasks

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] Tested changes locally.
- [ ] New tests added?
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #113 

#### Full Description of your Changes
I moved the javascript call for fontawesome to the bottom of the body and made it asynchronous. I also added critical css from the balloon.css file to the critical styles in the header. I only added the css that is currently used and I lazy loaded the rest. It's technically not necessary to load the rest of the css if you're fairly certain that you won't use the balloon tooltips in any manner other than how they're being used now.

### CODE REVIEW

**Comment by asiyani** [comment]
@collinmesser  Thank you for working on this for us. 
But changes you made are in `dist` folder. this folder is generated by gulp task. so it will be overridden.  Please makes changes to `src/views` folder. 
Thank you.

**Comment by collinmesser** [comment]
So after playing around some more, here are my thoughts on this fail. Lesslint is failing due to 190 "warnings". I adjusted a few of the warnings and got it down to 174. I don't think we should edit all of the css though because it's css written for the specific plugins (CodeMirror and Balloon Tooltips). My proposed solution is to add the  `failOnWarning: false` option to the lesslint rules. This would allow the warnings to persist but does not prevent the test from failing due to a warning. It would still have the test fail on errors though. I'm open to other ideas though if this is not an acceptable solution.

**Comment by joshghent** [comment]
@asiyani Thoughts?

**Comment by asiyani** [comment]
I am not sure about `lesslint` errors.
if it's just about the style of the code then we can accept that as warnings.
I mean to say if it's not going to affect the functionality of the website.

**Comment by joshghent** [comment]
@collinmesser Ok, do you want to go ahead and add `failOnWarning: false` as you said. And I will merge 👍 
Thanks for your work and looking into this! Appreciate you taking the time and not just abandoning it!

**Comment by joshghent** [comment]
Thanks @collinmesser, all merged! You've improved the PSI score by 20!

There's still work here I'd like to do but made a massive difference! Really appreciate your work 🎉

**Pull request merged**
