### PR TITLE
Less

### PR DESCRIPTION
**Pull request by SaraVieira**
Replace Stylus with less and order files

### CODE REVIEW

**Comment by joshghent** [comment]
@SaraVieira Nice work Sara that was quick work!
Are you able to resolve the merge conflicts in the files and also convert over the blog.css that was introduced in https://github.com/esfiddle/esfiddle/pull/57

Thank you for your work, look forward to merging it!

**Comment by SaraVieira** [comment]
It was fast work because the syntax is pretty much the same and this way I can start work on the design and mobile site 😄

**Comment by SaraVieira** [comment]
Btw are you okay with changing the color pallete of the website or is that off limits?

**Comment by joshghent** [comment]
@SaraVieira Yes changing the color palette is fine with me. That would be great. We want to completely redesign the site to make it more sleek and user friendly. I'll get your PR merged now. Thank you very much for all your work. You've been a great asset 👍

**Comment by joshghent** [comment]
Thanks for your work again @SaraVieira.

Look forward to your next PR! 🎉

**Pull request merged**
