### PR TITLE
Feature 119

### LINKED ISSUE #119: Make esfiddle profiles publicly accessible
We want to make esfiddle profiles accessible to anyone so they can see each others fiddles. 

This will require new API methods and routes to get a unique URL for each user (I recommend we use the mongo _id that is assigned to each user record.

We also need to add extra logic to the profile page to make sure that private fiddles are not shown in the users list of fiddles if they are not logged in as that user! For example if I am logged in as myself I should be able to see **ALL** of my fiddles, public or private. If someone else views my profile they should only be able to see public fiddles.

If you need any help with this issue then please let us know. We'd be happy to help. You can also check out our [contributing](https://github.com/esfiddle/esfiddle/blob/develop/docs/CONTRIBUTE.md) guide 👍

### PR DESCRIPTION
**Pull request by JeffKandel**
#### Pre-Submission Checklist
- [x] Your pull request targets the `develop` branch.
- [x] Branch starts with either `fix/` or `feature/`
- [x] All new and existing tests pass the command `npm test`.
- [NA] Any new files are included in the grunt tasks

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] Tested changes locally.
- [x] New tests added? (see note below)
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #119 

#### Full Description of your Changes
1) Added /profile/:_id route
    - redirects logged in user to /github/myProfile
    - fetches user based on the id
    - fetches that users public fiddles only
    - renders profile.ejs view
2) Added profile.ejs view
    - based on authenticated.ejs
    - does not include started fiddles
    - will display a static error message if passed _id variable
    - else will display user name, image, and public fiddles

I'm happy to take any feedback and update any of this approach.  I just wanted to provide something concrete as a first step.  If there are minimal changes, I'll fix it up and add some tests as well.  I held off on the tests in case I needed to take a different approach entirely.

J

### CODE REVIEW

**Comment by asiyani** [comment]
@JeffKandel thank you for working on this, Nice work!

few changes I would like to discuss with you and @joshghent.

1. You are using our db user ID which makes URL very long. I was thinking of using githubId which we have stored in our db for all registered users. 
             - current implementation 
                        http://localhost:3000/profile/592dd8820a98003dbb74d279
             - my suggestion
                        http://localhost:3000/profile/7142320
2. new profile file `profile.ejs` is same as `authenticate.ejs` apart from error message. I was thinking we should merge these 2 files into one. so that we don't have to make changes to both files.( There is an issue open to display fiddle title and description instead of fiddle number in the profile page.)
3. I think we should show stared fiddle by user as well on the public profile. if that stared fiddle is public.

4. When the user is not found, the server should send 404 as well with the static error message.

Please lets us know what's your thoughts are.

**Comment by joshghent** [comment]
@asiyani 

1. Not sure if I agree with you here as we may use other services (google, facebook, twitter etc) to sign up with in the future so may not always have a githubID. I think we need some way of making a 'friendly' url though. Maybe a new column called 'friendly' url that would be made up of their firstname and surname. If that url is taken then add a number to it or something. 

2. Completely agree. Could become tricky if we want to change something on the profile but not the auth view though. I think it's a fairly safe bet though as we can add logic in this case.

3. Agreed!

4. Again, agreed!

You've done a great job so far @JeffKandel this is amazing work!

**Comment by JeffKandel** [comment]
Good points all around, I will make some updates tomorrow as well as add some new tests.

Thanks!

**Comment by JeffKandel** [comment]
@asiyani or @joshghent

I made updates based on yesterday's conversation and included a profile test.  Here are some of my notes and some open questions I have.

Notes:
1) I left the mongo user _id as the profile id.
2) I switched the authenticated.ejs and profile.ejs views into the views/profile directory.  I abstracted the content into authenticated, public, and notFound sections as well as abstracting recentFiddles and starredFiddles into separate files.
3) Starred fiddles are not showed above recent fiddles.  Do you like this approach?  I could also sort the recent fiddles to put starred ones at the top and include a star icon in the <li>.  Happy to mock something else up if preferred.
4) Fixed! (This was just a mistake on my end)

5) Added profile.test.js to pass codecov.  I think the unit tests of the rendered views are a little underwhelming when compared to testing an API call (where you can check values res.body.  I mostly understand why this is, but  let me know if either of you have suggestions about how I could improve this?  

6) Are there any additional features you'd like to see in this PR.  I think some sort of "Share" button/popover on the github/myProfile view would be nice.  Otherwise no one will be able to find their user id...

**Comment by asiyani** [comment]
@JeffKandel Good work! Thanks for working on this.
@joshghent We will create a new issue for Share button as well as shortening URL for the public profile.

**Comment by joshghent** [comment]
@asiyani Good idea!

Thanks for your work @JeffKandel this looks great!

**Pull request merged**
