### PR TITLE
Added a line in the Gruntfile.js file so that the es6-fiddle.js file …

### PR DESCRIPTION
**Pull request by patelg123**
…is uglyfied/minified

#### Pre-Submission Checklist
- [ ] Your pull request targets the `develop` branch.
- [ ] Branch starts with either `fix/` or `feature/`
- [ ] All new and existing tests pass the command `npm test`.
- [ ] Any new files are included in the grunt tasks

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [ ] Tested changes locally.
- [ ] New tests added?
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Full Description of your Changes

### CODE REVIEW

**Comment by joshghent** [comment]
Great work dude! Does this improve the lighthouse score in the Chrome Dev tools?

**Comment by patelg123** [comment]
Hi Josh,

Yes it did improve.

Performance before minification was 31

image

and 43 after

image

**Comment by joshghent** [comment]
@patelg123 Awesome stuff! Looks like the next biggest improvement we can do is https://github.com/esfiddle/esfiddle/issues/280

**Comment by patelg123** [comment]
Thanks Josh, that's the one I was going to pick up next

**Pull request merged**
