### PR TITLE
Vertical fill

### PR DESCRIPTION
**Pull request by SaraVieira**
This pull requests adds:

- Horizontal and vertical fill
- Horizontal redimensions
- Fixes gruntfile problem in inline
- Styles dropdowns
- Adds flex to the layout

### CODE REVIEW

**Comment by joshghent** [comment]
@SaraVieira Great work thank you, looks amazing!
Couple of things to fix:
* In dark mode the result iframe goes black but the rest of the 'result-wrapper' does not. Perhaps make it so the iframe extends to 100% of the height of the result-wrapper.
* In horizontal mode you cannot resize the code/console windows.

I will merge when those couple of niggles are fixed. Thanks! 👍

**Comment by SaraVieira** [comment]
@joshghent All done !

Please try to run again 😄

**Comment by joshghent** [comment]
@SaraVieira That's really cool! Exactly what I wanted. Looks amazing. Thanks a lot!
We need your kind of skills in UI. If you have time please take a look at any of our issues or if you think the site could be improved in anyway, go ahead and do it! We'd be more than happy to accept PR's on design! [Here is one for improving the mobile design](https://github.com/esfiddle/esfiddle/issues/56).

Thanks a lot for your PR and look forward to your next one 👍 🎉

**Comment by joshghent** [comment]
@SaraVieira That's really cool! Exactly what I wanted. Looks amazing. Thanks a lot!
We need your kind of skills in UI. If you have time please take a look at any of our issues or if you think the site could be improved in anyway, go ahead and do it! We'd be more than happy to accept PR's on design! [Here is one for improving the mobile design](https://github.com/esfiddle/esfiddle/issues/56).

Thanks a lot for your PR and look forward to your next one 👍 🎉

**Comment by SaraVieira** [comment]
@joshghent Thank you so much!  I'm glad it's what you wanted :D

Sure,  I will take a look at some more issues and already commented on the one you referenced :)

**Pull request closed without merging**
