### PR TITLE
Add example for ES6 Math and Number features and update Iterator example

### PR DESCRIPTION
**Pull request by lautta**
#### Pre-Submission Checklist
- [x] Your pull request targets the `develop` branch.
- [ ] Branch starts with either `fix/` or `feature/`
- [x] All new and existing tests pass the command `npm test`.
- [ ] Any new files are included in the grunt tasks

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] Tested changes locally.
- [ ] New tests added?
- [x] Closes currently open issue (replace XXXX with an issue no): Adds to #74 

#### Full Description of your Changes
Added to example for iterators and created new example for new Math and Number features.

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hello @lautta,

First of all thank you so much for your PR, it's awesome you wanna help :D

Unfortunately the eslint task is failing on your branch, can you please take a look at that?

**Comment by SaraVieira** [comment]
Thank you so much @lautta. 

I think it's awesome to merge now, what do you think @joshghent?

**Comment by joshghent** [comment]
@lautta Thank you for your PR! 🎉 Great work.

Looks good @SaraVieira Would you like to merge?

**Comment by SaraVieira** [comment]
@lautta Merged ! Thank you so much for your contribution 🎉

**Pull request merged**
