### PR TITLE
Change docker login, add it in the run flow

### PR DESCRIPTION
**Pull request by jigar1101**
#### Pre-Submission Checklist
- [ ] Your pull request targets the `develop` branch.
- [ ] Branch starts with either `fix/` or `feature/`
- [ ] All new and existing tests pass the command `npm test`.
- [ ] Any new files are included in the grunt tasks

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [ ] Tested changes locally.
- [ ] New tests added?
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Full Description of your Changes

### CODE REVIEW

**Comment by joshghent** [comment]
Hi @jigar1101 - are you able to find a way to test this script locally please mate? Ideally want to just make one final PR to get all the work wrapped up. Well done though :)

**Comment by jigar1101** [comment]
@joshghent Since it pushes on the GitHub registry with the credentials stored on the Github itself, its not possible to test this locally.
I can understand your concern and my apologies for creating so many Pr's but didn't have any other choice to test the docker login and push.

**Comment by joshghent** [comment]
@jigar1101 All good mate, I have had to do the same thing before 👍

**Comment by jigar1101** [comment]
@joshghent Looks like no more PR's :)
https://github.com/esfiddle/esfiddle/packages/380487

**Comment by joshghent** [comment]
@jigar1101 That's awesome! Great work dude!

**Pull request merged**
