### PR TITLE
Remove dist folder

### PR DESCRIPTION
**Pull request by joshghent**
Stop annoying git conflict issues by removing the dist folder from source control and get Heroku to build the files! 

#### Pre-Submission Checklist
- [x] Your pull request targets the `develop` branch.
- [x] Branch starts with either `fix/` or `feature/`
- [ ] All new and existing tests pass the command `npm test`.
- [ ] Any new files are included in the grunt tasks

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [ ] Tested changes locally.
- [ ] New tests added?
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Full Description of your Changes

### CODE REVIEW

**Comment by joshghent** [comment]
There's a bug with this at the moment where running code will cause a JS error because it can't find babel inside the iframe.

**Comment by JeffKandel** [comment]
I was able to recreate the issue, but had no luck resolving it.

**Comment by joshghent** [comment]
Thanks @JeffKandel for looking into it.

@asiyani Any light you can shed on this?

**Comment by asiyani** [comment]
Hi all, 
I think I know why this is happening, but dont have solution yet...
so before we were loading babel from bist/lib. now we are loading from cdn using stand-alone. 
I am not sure which version we had in dist/lib.
Now when we load babel from cdn,  variable is not `babel` but its `Babel`
Important thing is it doesnt have `Babel.run()` function !!!!!

If you change following code in `index.js`
```
    bootstrap.innerHTML = (
                    'document.body.innerHTML = \'\';\n' +
                    'console.log(Babel.transform(document.querySelector(".babel-text").innerHTML,{ presets: ["es2015"] }).code);\n' +
                    'Babel.run(document.querySelector(".babel-text").innerHTML);\n'
                  );
```
`Babel.transform` is working it means babel is loaded but you get error Babel.run() is not a function.

**Comment by JeffKandel** [comment]
So I took Ashok's suggestions one step further and wrapped in it eval():
bootstrap.innerHTML = (
           'document.body.innerHTML = \'\';\n' +
           'eval(Babel.transform(document.querySelector(".babel-text").innerHTML,{ presets: ["es2015"] }).code);\n'
                  );

This worked for most of the example code I ran it with.  The Generators example throws an error related to babel.transform (maybe we need another preset?).

I'm curious what we think about using eval... I am hesitant but also unsure of another way to run the code...

**Comment by joshghent** [comment]
Great work guys, thanks for looking into this.

I understand the concern using `eval()`. Perhaps we could use [this](https://babeljs.io/docs/plugins/transform-runtime/)? It seems like maybe Babel.run was removed in favor of this transform-runtime module.

Let me know @JeffKandel @asiyani if we can port over to using this.

**Comment by asiyani** [comment]
Can't find any thing about `babel.run()`
Solution would be to keep `lib/` folder in dist and add rest in `.gitingnore`
anyway, lib folder will never cause conflict so it should be OK. if we can't fix this bug.

**Comment by joshghent** [comment]
@asiyani I guess that's a temporary work around. I'd like to transition over to do something more concrete with Babel, perhaps adapting it to how we need in the future. 

I'll do that and see if everything works. Thanks! 👍

**Pull request merged**
