### PR TITLE
Import javascript mode for CM syntax highlighting

### LINKED ISSUE #97: Fix code editor syntax highlighting
#### Type of issue
- [x] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
There is a bug currently on the development branch where the code editor will not display any syntax highlighting.

### PR DESCRIPTION
**Pull request by chrisself**
#### Pre-Submission Checklist
- [x] Your pull request targets the `develop` branch.
- [x] Branch starts with either `fix/` or `feature/`
- [x] All new and existing tests pass the command `npm test`.
- [ ] Any new files are included in the grunt tasks

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] Tested changes locally.
- [ ] New tests added?
- [x] Closes currently open issue: Closes #97 

#### Full Description of your Changes
Per the Code Mirror documentation, the language mode should be included. I've gone ahead and added an import statement to ensure it's a part of the bundle.

### CODE REVIEW

**Comment by joshghent** [comment]
Thanks for your PR @chrisself 🎉 
Looks great, however the syntax doesn't seem to be highlighting still. Maybe it's something I'm not doing. Can anyone else review this? @SaraVieira @vcapretz @asiyani @ironprice91

**Comment by chrisself** [comment]
Hey @joshghent. 

I deleted my local repository and cloned the new branch to test this out. It appears the file isn't bundled with the initial build. However, if I press save in `index.js`, it triggers a new build that includes the file. I'm not too familiar with Grunt, so I'll have to check out the configuration and documentation to learn more about why this is occurring.

**Comment by ironprice91** [comment]
Thanks for your PR @chrisself ! 👍 

@chrisself  @joshghent  I tested out your branch with the changes and it looks like the syntax highlighting is there if I'm not mistaken. So I think this should be good to merge?

screen shot 2017-03-26 at 9 39 17 am

**Comment by joshghent** [comment]
@chrisself @ironprice91 Apologies for the delay here. Thanks for checking it out. I'll get this merged now.
Thanks a lot @chrisself for your PR 🎉 We'd be very happy to have you as part of our growing community. Join our gitter [here](https://gitter.im/esfiddle/Lobby)

**Pull request merged**
