### PR TITLE
improve example code for promises - part of #74

### PR DESCRIPTION
**Pull request by sanggonlee**
#### Pre-Submission Checklist
- [ ] Your pull request targets the `develop` branch.
- [ ] Branch starts with either `fix/` or `feature/`
- [ ] All new and existing tests pass the command `npm test`.
- [ ] Any new files are included in the grunt tasks

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [ ] Tested changes locally.
- [ ] New tests added?
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Full Description of your Changes

### CODE REVIEW

**Comment by joshghent** [comment]
@sanggonlee Thank you very much for your PR! 🎉 
I will review this code and test it locally tomorrow.

Thanks a lot for your help here. We really appreciate it! We are still accepting PR's on this issue so if you would like to improve more of the example code then please go ahead! 👍

**Comment by SaraVieira** [comment]
@joshghent Can I merge this PR?

**Comment by joshghent** [comment]
@SaraVieira Yeah sure thing! All yours 👍

**Comment by SaraVieira** [comment]
@sanggonlee  Merged ! Thank you so much for your contribution 🎉

**Pull request merged**
