### PR TITLE
Fix issue 73

### PR DESCRIPTION
**Pull request by Kashyap12**
Split app.js into 3 smaller files within routes folder

#### Pre-Submission Checklist
- [x] Your pull request targets the `develop` branch.
- [ ] Branch starts with either `fix/` or `feature/`
- [ ] All new and existing tests pass the command `npm test`.
- [ ] Any new files are included in the grunt tasks

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [ ] Tested changes locally.
- [ ] New tests added?
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Full Description of your Changes

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hey! 

First of all thank you so much for your PR but unfortunately the node unit tests are failing :(

**Comment by Kashyap12** [comment]
@SaraVieira Yeah, I ll try to ifx it and submit a new pr

**Comment by joshghent** [comment]
@Kashyap12 Thanks for your PR! 🎉 

It still looks like the travis build is failing however, could you please try and fix this before I merge.

Please let us know if you need any support with this.

**Comment by Kashyap12** [comment]
hi @joshghent The latest PR passed the test, could yoou please cross check once

**Comment by joshghent** [comment]
@Kashyap12 I don't think you've pushed your changes!
When you push them, travis will run the test suite and double check that all tests pass 👍

**Comment by joshghent** [comment]
@Kashyap12 Hi there, I'm going to close this for now. Please reopen the PR when the test cases are fixed.

Let us know if you need any help 👍

**Pull request closed without merging**
