### PR TITLE
Create es7-includes-index-example.js

### PR DESCRIPTION
**Pull request by lautta**
New example of includes demonstrating search by index argument and searching for undefined and NaN elements

In response to issue #74

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hello @lautta,

First of all thank you so much for your PR, you are awesome 🏆 

I do have a problem when running this:

```
    'console.log(array.includes('a', 0));',
    'console.log(array.includes('a', 1));',
    '',
    '//negative is used as the offset from end of array',
    'console.log(array.includes('a', -6));',
    'console.log(array.includes('a', -5));',
```

I get a fatal error, you need to surround the a's in double quotes , as soon as this is done I can merge 😄

**Comment by lautta** [comment]
Thanks for the help! Sorry about that. I have now fixed that issue.

**Comment by SaraVieira** [comment]
No problem, thank you for your contribution 👍 

I'll get @joshghent merge this 🎉 

Thank you again @lautta

**Comment by joshghent** [comment]
Amazing @lautta! Thank you for your contribution! We are looking for more contributions for this issue, so if you have any more ideas then we'd be happy to welcome more PR's! 🎉  Or you can check out our[ other issues](https://github.com/esfiddle/esfiddle/issues). Come and chat with us on [Slack](esfiddlejs.slack.com) too.

**Pull request merged**
