### PR TITLE
Fix: #141 - optimize mobile profile

### LINKED ISSUE #141: Optimize profile for mobile
#### Type of issue
- [x] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)

The profile needs a redesign especially considering it doesn't look very good on mobile and on desktop I don't think it uses the space as well as it could. Go wild with this one and be adventurous! Idea's are encouraged even if you cannot implement it. 

Information we need to have accessible on the profile
- Recently created fiddles
- Starred fiddles
- Private fiddles (if you are logged in as that user)

If you want a second thought before you start also, then please just reply with a screenshot and we'll jump in with feedback!

capture

### PR DESCRIPTION
**Pull request by colinxr**
#### Pre-Submission Checklist
- [x] Your pull request targets the `develop` branch.
- [x] Branch starts with either `fix/` or `feature/`
- [x] All new and existing tests pass the command `npm test`.
- [ ] Any new files are included in the grunt tasks

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] Tested changes locally.
- [ ] New tests added?
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #141 

#### Full Description of your Changes
I redesigned the profile page to fit mobile devices and make better use of space on desktop. I divided the previous profile card into two separate sections – one for user details (name, avatar, github url), and another for the users' actual fiddles.

### CODE REVIEW

**Comment by joshghent** [comment]
@colinxr Thank you for this! Great work so far. Couple of things I noticed.

1. It seems to say I have 0 fiddles even though I have 2 shown in recent.
2. The link to my github is a relative link so it will link to localhost:3001/github.com/joshghent rather than the direct URL.

**Comment by colinxr** [comment]
Hey @joshghent, take a look at the latest commit and let me know!

**Comment by vcapretz** [comment]
Hi @colinxr, thank's for the PR! I noticed that your merge request has some conflicts, could you please solve them?

**Comment by joshghent** [comment]
Hey @colinxr, thanks for this PR. I have now merged it! 🎉 
Thank you again for your contribution. Without your hard work, ESFiddle would not be possible 👍

**Pull request merged**
