### PR TITLE
Trevor

### PR DESCRIPTION
**Pull request by SaraVieira**
@joshghent Can you please test on your machine ?

### CODE REVIEW

**Comment by joshghent** [comment]
@SaraVieira Phew! Quick work! Thanks.

I didn't realise this required docker to work. That's a pain. I can't seem to find any other way to run travis locally though. Ideally we want to make sure it's as easy as possible for people to get stuck in, rather than make them configure all this stuff. 

Perhaps we can accept this PR for maintainers as I would personally find it useful. However I don't think we should configure as a pre-push hook. Maybe just on the develop branch which maintainers will work on.

**Comment by SaraVieira** [comment]
That's exactly what I wanted to talk to you about, this requires a lot of time to run and it needs docker to be installed and running so it may not be a great asset for a hook. 

But we should run npm run tests on pre-push I think so it's a matter of changing the issue

**Comment by joshghent** [comment]
@SaraVieira Yeah I think you're right. Let's do that. Sorry if this seemed like a waste of time. I completely didn't realise.

Let's do that.

**Comment by SaraVieira** [comment]
@joshghent It wasn't useless, we learned something and we can test the build locally so I would say the 10m I spent were pretty good 👍

**Pull request closed without merging**
