### PR TITLE
Image caching

### PR DESCRIPTION
**Pull request by ironprice91**
Updated app.js to use a simple caching function to set the Cache-Control based on request.url regex for images (set to one month)

Here's the initial load:
screen shot 2017-02-16 at 10 48 31 am

And the next load with caching
screen shot 2017-02-16 at 10 48 47 am

Response Headers:
default

Anything I should update here? I'd love some feedback, thanks!

### CODE REVIEW

**Comment by joshghent** [comment]
That's awesome and a test too! Great job @ironprice91 👍 
Would it be possible to include /lib/babel/babel.min.js in the cache include as well?

**Comment by ironprice91** [comment]
Thanks @joshghent 😄 
Did you want to have the /lib/babel/babel.min.js also cache for a month as well?

**Comment by joshghent** [comment]
@ironprince91 yes please!

**Comment by joshghent** [comment]
@ironprice91 Brilliant, looks good. The travis thing breaking is my fault. I'll fix that up.

**Comment by ironprice91** [comment]
@joshghent sounds good, I look forward to contributing more in the future! Thanks 🎉

**Comment by joshghent** [comment]
@ironprice91 Look forward to it, thanks a lot! We're looking for more long term maintainers so that would be great 👍

**Pull request merged**
