### PR TITLE
Added active node versions up through v7.  Major numbers and current release

### PR DESCRIPTION
**Pull request by musicionary**

### CODE REVIEW

**Comment by musicionary** [comment]
@joshghent Do you have some insight on the travis build logs.  These are the two types of errors I'm seen:

1. On v4 and v5 the build is reporting of a syntax error in test/api.test.js
2. On v0.10 and v0.12 the build is reporting errors related to something with eslint and grunt-contrib-stylus.

If you have any suggestions, I'd appreciate it!

**Comment by joshghent** [comment]
@musicionary Great work, thanks for your PR. It's not a problem if they fail currently. We will get them fixed up. I think another PR I have open will be able to solve most of the issues.

Thanks a lot for your work! 👍 🎉 

Take a look at our other [issues](https://github.com/esfiddle/esfiddle/issues) or make a new one if you have an idea for the project. We'd be happy to welcome new suggestions.

**Comment by asiyani** [comment]
I think you might get syntax error in test/api.test.js file with old version of node. 
Because I have used arrow function syntax in that file.

**Comment by joshghent** [comment]
@asiyani Yeah I was going to ping you to see what the issue might be.
Since going forward we want to be using ES6, maybe we should not support those older node versions. I mean really we only **need** to support the latest version of node but in the future then we may want backwards compatibility.

**Pull request merged**
