### PR TITLE
fix #1 Update README.md 

### LINKED ISSUE #1: Improve the README
OK so the readme contains basic setup but we need to point people to the contributing guide and filing bug reports.

Like the readme on [Freecodecamp](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/README.md)

### PR DESCRIPTION
**Pull request by italo-batista**
I also add a REPORTBUG.md

### CODE REVIEW

**Comment by italo-batista** [comment]
Can I try?
Please, check my pull request! :)

**Comment by joshghent** [comment]
Great work @italo-batista that's perfect! There are more docs to update so I'll put an issue or two up and perhaps you can tackle them 😁 

Approved. Fixes https://github.com/esfiddle/esfiddle/issues/1

**Comment by joshghent** [comment]
@italo-batista https://github.com/esfiddle/esfiddle/blob/develop/CONTRIBUTORS.md 👍

**Comment by italo-batista** [comment]
Thanks, @joshghent ! 
It will be a pleasure contribute more times for the project.

**Pull request merged**
