### PR TITLE
feature: "Star" fiddles #2

### LINKED ISSUE #2: "Star" fiddles
So the idea here is that other people will be able to "Star" your fiddles. The most starred fiddles will then be displayed on a page like a hall of fame type thing but this will be added in the future.

The first job is to add a route for '/star/:fiddleID' which will save a star against that fiddle.
The second task for this PR is to add a Star button on the fiddle page (only when it is saved!) that will make a call to this route.

The rest will be handling in future issues and PR's, let's just get the functionality in place first.

### PR DESCRIPTION
**Pull request by asiyani**
#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] Tested changes locally.
- [x] New tests added?
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #2 

### Only Logged in user can star any fiddle. 
Added API to star fiddle
Added start button on front end. 
Added stared fiddle section in profile page for logged in user. 

Need to write test for POST '/star/:fiddleID'

### CODE REVIEW

**Comment by asiyani** [comment]
Added test for post star/:fiddleID. 
Not sure why but test for cache is failing !

**Comment by joshghent** [comment]
@asiyani Nice work!
I seem to get the following output however when running `npm start` any ideas?
```bash
(node:18771) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Running "express:dev" (express) task
Starting background Express server
Express version 4.14.0 starting server on port 3000.

Running "browserSync:bsFiles" (browserSync) task

events.js:160
      throw er; // Unhandled 'error' event
      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/Users/josh/Projects/es6-fiddle-web/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/josh/Projects/es6-fiddle-web/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:272:12)
    at Connection.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/josh/Projects/es6-fiddle-web/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Socket.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Stopping Express server
```

**Comment by asiyani** [comment]
That's mongodb server error... 
Do you have mongodb server running?

**Comment by joshghent** [comment]
I just realised that's why. I rebooted my macbook yesterday for updates and it stopped the server. I literally always have mongo running. My bad! 😆

**Comment by joshghent** [comment]
@asiyani Wow looks great, I've wanted this feature for ages! 👍 

Would it be possible to perhaps return the errors into [toasts](https://www.w3schools.com/howto/howto_js_snackbar.asp)?
So when I click the star button on an unsaved fiddle it will return a toast that says "Please first save and sign in to star the fiddle."
And when starring a fiddle when not signed in then return the message you've already got but just to a toast.

**Comment by asiyani** [comment]
Ya sure I can look in to that....

**Comment by joshghent** [comment]
@asiyani Thanks a lot. That's just an idea, it seems like the best non-intrusive way to inform the user of an error.

What do you think?

**Comment by asiyani** [comment]
Yes you are right.... At the moment my error message might replace users code so not good....

**Comment by asiyani** [comment]
Added snackbar for Error message.

**Comment by joshghent** [comment]
@asiyani Awesome, looks amazing. Code is great too! Thanks a lot 🎉 
I'll get that merged in. Nice work 👍

**Pull request merged**
