### PR TITLE
Feature/dynamically loading js libraries

### LINKED ISSUE #46: feature: loading 3rd party javascript library
User should be able to load 3rd party library and do some coding on that. 

e.g. 
User should be able to load lodash library and then run following fiddle to get response in console page.

```
var object = { 'a': { 'b': 2 } };
var other = _.create({ 'a': _.create({ 'b': 2 }) });
 
_.has(object, 'a');
// => true
 
_.has(object, 'a.b');
// => true
 
_.has(object, ['a', 'b']);
// => true
 
_.has(other, 'a');
// => false
```

### PR DESCRIPTION
**Pull request by jigar1101**
#### Pre-Submission Checklist
- [x] Your pull request targets the `develop` branch.
- [x] Branch starts with either `fix/` or `feature/`
- [x] All new and existing tests pass the command `npm test`.
- [ ] Any new files are included in the grunt tasks

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] Tested changes locally.
- [ ] New tests added?
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #46 

#### Full Description of your Changes

Dynamically load javascript libraries.
-Added a select option for user to select the library from an existing list/dropdown.
-When the user selects the library, dynamically create a script tag and append in head

### CODE REVIEW

**Comment by joshghent** [comment]
@jigar1101 Hi there, thanks for your contribution, this looks great! Would it be possible to rebase against the current version of the development branch. I changed up the travis script so hopefully this should fix the test issues. Then I will test it out 👍

**Comment by jigar1101** [comment]
@joshghent I've rebased the branch! There are certain commits that are not there in my branch but are reflecting in this PR inspite of rebasing!
Are you currently working on any more changes? Let me know if I should create a new PR or once you're done.
Great work updating the travis script! 👍

**Comment by joshghent** [comment]
@jigar1101 Brilliant, thanks so much for doing that. I've re-deployed the app and spotted a couple of issues.

1. All the libraries I tried to use (jQuery, Underscore, Lodash) didn't appear to be working. You can try this out on [https://esfiddle-pr-174.herokuapp.com/](https://esfiddle-pr-174.herokuapp.com/) which is the test app for your pull request.
2. When saving a fiddle that uses a library we need to make sure we save that with the fiddle and also load that library in when we view that fiddle.

Couple of issues to address and then looks good to go! Thanks for your work on this, genuinely one of the best features to be added to ESFiddle! 💯

**Comment by jigar1101** [comment]
@joshghent Thanks for the appreciation! 
I have updated the code to load the libraries inside the iframe and now you'll be able to use the library, earlier the libraries were loading but they were loading inside the top frame as a result it was not usable. Have checked on https://esfiddle-pr-174.herokuapp.com/ and now one can use it :-)

Regarding the saving and loading of libraries, i've started work on it. Just incase if you want to merge this PR you can merge it.
I'll update the save feature in a weeks time and create a new PR for it.

And regarding the Greenkeeper, would like to love on it. I'll take that up post the save feature.

**Comment by joshghent** [comment]
@jigar1101 Hey man, great work!
Spotted an additional issue here. Below are the steps to reproduce:

1. Create a fiddle using a library (for example, the example code with underscore).
2. Select to use the library for your code
3. Run the fiddle
4. Save the fiddle - this will redirect you to the fiddleID page
5. Re-select the library in the dropdown
6. Re-run the fiddle

It doesn't seem to work. The only solution is hard refresh and clear your cache. I'm not entirely sure how you're loading the libraries in, but I assume they are caching in the wrong frame or something.

In terms of reloading the library for saved fiddles, after considering this, at first I thought we could merge this and get it released. But on reflection, after using this feature for a while, I think it's a necessary thing to get this done for the first release of this feature. And seeing as you're already working on it and know what you're doing then should be all good 👍 

Again thanks for your work here, don't worry about the issues. This is a massive feature and to be expected!

**Comment by jigar1101** [comment]
Hey @joshghent 
I checked the steps you mentioned but could't replicate the issue.
Just open this saved fiddle https://esfiddle-pr-174.herokuapp.com/jdk7k8jb/
Try loading jquery and then underscore manually as of now from the dropdown.
And then run the fiddle.

I'm able to run it without errors.
Let me know about you! (May be your previous code might have got cached)

**Comment by joshghent** [comment]
@jigar1101 Hmm, so still getting the issue intermittently but I checked on Incognito mode (without all my browser addons) and it worked fine so something my end is causing the issue. Either way looks great.

Final thing to add then is the save! Is that something you can do (think you said you were already working on it)? 💯

**Comment by jigar1101** [comment]
Yeah, had started debugging, noted the changes to be made and was going through the backend flow. Hopefully, will finish it off in this week. :-)

**Comment by joshghent** [comment]
@jigar1101 Brilliant, look forward to it! No rush on it! Be with your family and friends first - they deserve more attention than this project 😁 Do it in your free time 😀 👍

**Comment by jigar1101** [comment]
@joshghent I'm done with the changes, you can review it once. 😁

**Comment by joshghent** [comment]
@jigar1101 Going to review this on Monday as I'm off for the weekend! Thanks for getting this done, after having a quick read it looks great! Can't wait to get this out! 🎉

**Comment by joshghent** [comment]
@jigar1101 Ok brilliant, saving is working brilliantly.
Last issue to fix is when loading a fiddle that has a library, we need to select it in the Library dropdown!

Thanks a lot for your great work. Code looks great. Will merge after this is fixed! 👍

**Comment by jigar1101** [comment]
@joshghent Are you talking about loading a saved fiddle with libraries? I have already done that! 
You can check it here, https://esfiddle-pr-174.herokuapp.com/jdv2kst5/
I have saved the backbone and underscore libraries and they are loading.

Can you elaborate the issue you are facing or clear the cache and try?

**Comment by joshghent** [comment]
@jigar1101 ah I see, so you can load multiple libraries at a time! Got it.

In that case, let's do the following.
1. Covert the libraries box to a "select multi" (see https://www.w3schools.com/tags/att_select_multiple.asp)
2. On load of a fiddle that uses a library, set the relavent libraries to be selected in the drop-down so *visually* I can see (you have already done the hard part of loading those libraries - we just now need to display that to the user) that the fiddle uses those libraries.

Hopefully that makes sense!

**Comment by jigar1101** [comment]
@joshghent That sounds cool! But the only concern I see here is that the selection header which has dropdown currently will expand to a size to cover all the libraries which will make the console and coding area to decrease. 
We need to figure out an apt place where we can place the multiple selection box without affecting the current code and console areas.

**Comment by joshghent** [comment]
@jigar1101 Ok so I'd keep the box in the same place and add a max-width to it. Then when displaying the library names, just comma seperate them and add an ellipsis if it becomes too long (although I think this is the behaviour of the browser already)

In the future, we may just move this to a modal UI like on Codepen with tabs for other settings. So if you're feeling adventurous, perhaps make something like that? But tbh, for the scope of this PR, the first solution (max-width) is more than adequate.

I will make another issue to address the UI, It all needs overhauling really.

Thanks! 💯

**Comment by jigar1101** [comment]
@joshghent I'm afraid the solution you suggested wouldn't be possible as the multi select box has the values each on new line and cannot be separated by comma.
Instead other option is to use the existing dropdown and show the list of libraries that are loaded. Below are the demos for it. 

More than the max width (Show ellipsis)

screen shot 2018-02-24 at 12 07 00 pm

Incase of single library loaded

screen shot 2018-02-24 at 12 07 21 pm


Let me know what you think about it. Will integrate it then.

**Comment by joshghent** [comment]
@jigar1101 Ah of course! I was thinking in jQuery land. Apologies...

Hmm that's a pretty good solution for now. I'd be keen to get this into a separate modal along with the other settings to make the UI cleaner. Happy to merge if you do the solution you proposed tho, think you've done more than enough here!

**Comment by jigar1101** [comment]
@joshghent The changes are done! You can merge it finally 💯

**Comment by joshghent** [comment]
@jigar1101 Looks fantastic mate, thank you so much. Really appreciate all the hard work here.
I've added you as a contributor so you can get working on the project more. We'd love to have your help.
I don't have a huge amount of time to dedicate to the project so could do with generous people like yourself to lovely donate their time to this project 👨‍💻❤️

**Comment by jigar1101** [comment]
@joshghent Sure! Thanks :-)

**Pull request merged**
