### PR TITLE
Feature/grunt eslint

### PR DESCRIPTION
**Pull request by tarang9211**

### CODE REVIEW

**Comment by tarang9211** [comment]
@joshghent i've added the basic framework for grunt and eslint. do have a look when you get a chance!

**Comment by tarang9211** [comment]
Any suggestions on this?

**Comment by joshghent** [comment]
@tarang9211 I know why it is failing. I will fix it and merge. Thanks a lot for your work. 🎉

**Comment by joshghent** [comment]
Completed in https://github.com/esfiddle/esfiddle/issues/17

Thank you to @tarang9211 for his work 👍

**Comment by joshghent** [comment]
@tarang9211 https://github.com/esfiddle/esfiddle/blob/develop/CONTRIBUTORS.md 👍

**Pull request merged**
