### PR TITLE
Added Title and Description for fiddles

### LINKED ISSUE #102: Adding Title and Description to fiddles
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)

@joshghent suggested that we should add a Title and Description to each fiddle. 

I think one way we can do this is instead of showing a blank console when initially selecting a fiddle example, we can provide a brief description of what the example is for and explain the code as well.

This would only be displayed when you select first select an example but would disappear once you run the code and the only way for it to show again would be to reselect the example.

This is just an idea, if anyone has any other suggestion please let me know! @SaraVieira

esfiddle - title and description on fiddles

### PR DESCRIPTION
**Pull request by BrianChen**
#### Pre-Submission Checklist
- [x] Your pull request targets the `develop` branch.
- [ ] Branch starts with either `fix/` or `feature/`
- [ ] All new and existing tests pass the command `npm test`.
- [ ] Any new files are included in the grunt tasks

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [ ] Tested changes locally.
- [ ] New tests added?
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #102 

#### Full Description of your Changes

### CODE REVIEW

**Comment by SaraVieira** [comment]
@BrianChen You have conflicts :(

**Comment by joshghent** [comment]
@BrianChen Have you had time to look into this?

**Comment by BrianChen** [comment]
Sorry have been busy recently, I will look into this this week.

**Comment by joshghent** [comment]
Hi @BrianChen Thanks for looking into this!

I just made a PR app for it. For some reason it doesn't appear to be working! https://esfiddle-pr-111.herokuapp.com/ 

It looks like we have a 404 for the primary JS file

**Pull request closed without merging**
