### PR TITLE
Feature/faq update

### PR DESCRIPTION
**Pull request by rosnovsky**
#### Pre-Submission Checklist
- [x] Your pull request targets the `develop` branch.
- [X] Branch starts with either `fix/` or `feature/`
- [X] All new and existing tests pass the command `npm test`.
- [X] Any new files are included in the grunt tasks

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [X] Tested changes locally.
- [ ] New tests added?
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Full Description of your Changes

Added a FAQ page based on FAQ.md to the website. Updated static routes, views, grunt task and page navigation as well.

### CODE REVIEW

**Comment by joshghent** [comment]
@rosnovsky 🙌 Awesome job! Thanks for your work 👍 
I'll get this merged later.

**Comment by rosnovsky** [comment]
Just added a couple of basic tests for static routes (and `/`) as well. It should improve test coverage, including for new `/faq` route ✨ Is there a way to force Codecov to re-evaluate this PR, does anyone know?

**Comment by rosnovsky** [comment]
Ok, it didn't work. @joshghent could you please point me in the direction of addressing this codecov failure, when you have a moment?

**Comment by joshghent** [comment]
Hi @rosnovsky, apologies for not getting back to you on this one!
The codecov report does not matter a great deal. All we need to sort now is those merge conflicts! If you get those resolved then I will merge this.

Thank you so much for your work, the code looks good to go! 🎉

**Pull request closed without merging**
