### PR TITLE
Add blog

### PR DESCRIPTION
**Pull request by galxzx**
Added a blog button to the navbar, routes for the blog using Poet, and ejs templates.

### CODE REVIEW

**Comment by joshghent** [comment]
Thanks for your work @galxzx. I'll check this out tonight. And get it merged :+1:

**Comment by joshghent** [comment]
@galxzx Great work, thanks a lot! Well done on your first ESFiddle PR! 🎉 We'd love to have you working on[ future issues](https://github.com/esfiddle/esfiddle/issues).

**Comment by galxzx** [comment]
@joshghent Thanks. I'll keep an eye out for future issues. It looks like most have someone working on them at the moment.

**Comment by joshghent** [comment]
@galxzx If you have an idea for something that could be improved (like modulerizing the routes in app.js) that would be great. We'd be more than happy to accept PR's. 
Thanks for your help. Look forward to your next PR :tada: :+1:

**Pull request merged**
