### PR TITLE
add-vijay-kumar

### LINKED ISSUE #126: navigators are using different font family when when navigated from About -> Blog
#### Type of issue
- [1 ] Bug
- [x] Idea/Suggestion--We need to make them consistent
- [x] Question--Is this a valid bug?

#### Description (include any screenshots or debugging information if applicable)
Screenshot:
image

When navigated to blog
image

I would like to work on this!!

### PR DESCRIPTION
**Pull request by VijayVj7**
#### Pre-Submission Checklist
- [ ] Your pull request targets the `develop` branch.
- [ ] Branch starts with either `fix/` or `feature/`
- [x] All new and existing tests pass the command `npm test`.
- [ ] Any new files are included in the grunt tasks

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)

#### Checklist:
- [x] Tested changes locally.
- [x] New tests added?
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #0126

#### Full Description of your Changes
made few changes as part font-family in navigators in UI.Made them consistent

### CODE REVIEW

**Comment by asiyani** [comment]
HI, @VijayVj7 Thank you very much for working on this. 

I have reviewed all changes you made. unfortunately, there are few issues we need to address before we can merge this PR.

1. You made all changes in `Dist/` Folder, we are using grunt to auto generate `Dist/` folder content in production. So any changes made into this folder will be overridden. You need to make changes to `style/` folder in Root directory. 
sc1

2. You missed out to make a change to profile page. 
        Main page
image
        Profile page
image

3. Not sure why you changed font family to 'kumar one'?

Please look into these issues and resubmit or update this PR.

Once again thank you very much for working on this issue for us. If you need any help let us know.

**Comment by asiyani** [comment]
Hi @VijayVj7 ,
Did you have time to look into this ?
I have added `less` task to `dev` script as well. if you fetch new commit `dist` folder will automatically generate.

**Comment by VijayVj7** [comment]
Hi Ashok,
Sorry for the delay,
today I will do it  and I will come back if I have any doubts,

**Comment by VijayVj7** [comment]
Hi Ashok,
I have few doubt, I changed in Dist/Style,
But I'm unable to know where I should in change in Style folder. Could you
please help me out in this.

I've changed the line Number: 5.
And can you let me know whether the entire website consumes only this
.header class.So any changes in this .header class should reflect the
entire header section in any website.

Could you please let me know if my understanding is correct.

You can contact me at :+91-9704004132. (whatsapp me)

[image: Inline image 2]

**Comment by asiyani** [comment]
@VijayVj7  I am sorry for later reply, 
Yes you are right style->components->header.less is used for all pages. 

But I think this issue is now fixed after  #128, I am not getting different font size anymore on my local machine.
could you please update your repo. and re-test.

**Comment by joshghent** [comment]
@VijayVj7 Have you had a chance to look at this?

**Comment by asiyani** [comment]
@joshghent I think this one is now fixed after  #128.

**Pull request closed without merging**
